version: '3.1'

services:
  nginx:
    image: journalr/nginx
    build: ./nginx/
    container_name: nginx-container
    ports:
    - 443:443
    links:
    - php
    volumes:
    - ./www/:/var/www/
  php:
    image: journalr/php
    build: ./php/ 
    container_name: php-container
    # tty: true
    expose:
      - "9000"
    volumes: 
      - ./www/:/var/www/
    secrets:
      - google_secret

  app-data:    
    image: php:7.0-fpm
    container_name: app-data-container  
    volumes:  
      - ./www/:/var/www/  
    command: "true"
  mysql:    
    image: journalr/mysql
    build: ./mysql/  
    container_name: mysql-container  
    volumes:  
      - /var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d/sql.sql
    environment:   
      MYSQL_DATABASE: data
      MYSQL_USER: datauser
      MYSQL_PASSWORD: TEMP   
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
    secrets:
      - db_root_password

  mysql-data:    
    image: devilbox/mysql:mariadb-10.3  
    container_name: mysql-data-container  
    volumes:  
      - /var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d/sql.sql
    command: "true" 

volumes:
 unused:

# //TODO Create docker network for docker stack 

secrets:
  db_root_password:
    # external: true // For when docker stack is running
    file: ./secrets/db_root_password.txt
  google_secret:
    # external: true // For when docker stack is running
    file: ./secrets/google_secret.txt
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx-container
  #   ports:
  #     - 80:80
  #     - 443:443

      
      